module.exports = {
    "act.ati": "Action token is invalid.",
    "act.atv": "Action token has been verified",
    "grp.seg": "Skipped existing group",
    "grp.gae": "Group already exists",
    "grp.gnm": "Group name missing",
    "grp.flg": "Failed to load group",
    "grp.ynp": "You have no permission to the group",
    "usr.prc.une": "User does not exist",
    "usr.bll.dud": "Duplicate users detected",
    "usr.prc.unp": "Incorrect account or password",
    "usr.prc.unr": "User account has not been confirmed and can't login.",
    "usr.bll.cnm": "Incorrect code. Try again.",
    "usr.bll.epd": "Code has expired. Try again.",
    "usr.bll.lhe": "The link has already expired",
    "usr.prc.abd": "This account has been deleted. If you want to register again, please call 400-850-1689.",
    "usr.prc.uas": "User account has been Suspended.",
    "usr.prc.ual": "User account has been locked out due to too many failed attempts",
    "usr.bll.ill": "Invalid link",
    "usr.aut.iut": "Invalid user token",
    "usr.aut.ute": "The user token has already expired",
    "usr.bll.ana": "Action token is no longer available",
    "usr.bll.ivp": "Invalid phone number",
    "usr.bll.ive": "Invalid email address",
    "usr.dto.mea": "Missing email address",
    "usr.aut.mss": "Invalid service name or missing security setting",
    "usr.svc.slg": "Successfully logout",
    "usr.dto.maa": "Missing action token id or auth code",
    "usr.dto.map": "Missing action token id or password",
    "usr.dto.pbs": "Passwords should be the same",
    "usr.dto.ovn": "You can only view your own data.",
    "usr.bll.asd": "Invalid tokens. Access denied.",
    "pub.asg": "Access Granted.",
    "pub.fld": "Failed to load data",
    "usr.aut.mrp": "You don't have required permission to perform the operation."
};
