/*jslint node:true*/
let BotSchema = require('../../framework/BotSchema.js'),
    DbConnections = require('../../framework/DbConnections.js'),
    apifyTwitterProps ={
        type: {type: String},
        id:  {type: String},
        url:  {type: String},
        twitterUrl:  {type: String},
        text:  {type: String},
        fullText:  {type: String},
        source:  {type: String},
        retweetCount: {type: Number},
        replyCount: {type: Number},
        likeCount: {type: Number},
        quoteCount: {type: Number},
        viewCount: {type: Number},
        createdAt: {type: String},
        lang: {type: String},
        bookmarkCount: {type: Number},
        conversationId:  {type: String},
        IsSended: {type: Boolean},
        TwitterText: {type: String},
        author: {
          type: {type: String},
          userName: {type: String},
          url: {type: String},
          twitterUrl: {type: String},
          id: {type: String},
          name: {type: String},
          profilePicture: {type: String},
          description: {type: String},
          location: {type: String},
          followers: {type: Number},
          following: {type: Number},
          status: {type: String},
          createdAt: {type: String},
          fastFollowersCount: {type: Number},
          favouritesCount: {type: Number},
          mediaCount: {type: Number},
          statusesCount: {type: Number},
        }
      },
    ApifyTwitter = new BotSchema(apifyTwitterProps);
exports.ApifyTwitter = DbConnections.quantum_common.model('ApifyTwitter', ApifyTwitter, 'ApifyTwitter');
